co_music/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls", namespace="users")),  
    path('', include("web.urls",namespace='web')),
]
if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.contrib import admin
from django.urls import path,include

from web.views import index,join_room,create_room,delete_room,leave_room,upload_music,toggle_playback,update_position,get_song_data,fetch_next_song,get_playback_status


app_name = 'web'

urlpatterns = [
    path('',index,name='index'),
    path('room/<int:id>',join_room,name='join_room'),
    path('create_room/',create_room,name='create_room'),
    path('delete_room/<int:code>',delete_room,name='delete_room'),
    path('leave_room/<int:code>',leave_room,name='leave_room'),
    path('upload/<int:room_code>',upload_music,name='upload_music'),
    path('toggle_playback/<int:room_code>',toggle_playback,name='toggle_playback'),
    path('update_position/<int:room_code>/', update_position, name='update_position'),
    path('get_song_data/<int:room_code>/', get_song_data, name='get_song_data'),
    path('fetch_next_song/<int:room_code>/', fetch_next_song, name='fetch_next_song'),
    path('get_playback_status/<int:room_code>/', get_playback_status, name='get_playback_status'),
]

templates/web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/music-favicon.jpg' %}">
    <title>SyncX | Home</title>
</head>
<body>
    <div class="bg flex">
        <header class="main">
            <h1 class="left"><span>Sync</span>X.</h1>
            <ul>
                <li><span>A</span></li>
            </ul>
        </header>
        <section id="hero">
            <section class="wrapper">
                <div class="left">
                    <h1>ENJOY <br> THE SONG <br> <span>TOGETHER.</span> </h1>
                </div>
                <div class="right">
                    <button><a  style='text-decoration : none;color : #fff;' href="{% url 'web:create_room' %}">Create Room</a></button>
                    <p>Create room and enjoy the music with your friends.</p>
                    <button id="join-room">Join Room</button>
                    <p>Join others room with redeem code and enjoy the music together.</p>
                </div>
            </section>
        </section>
        <footer>
            <div class="left">
                <p>Developed by <a href="https://www.instagram.com/nexift.team/" target="_blank" title="https://www.instagram.com/nexift.team/">Nexift.Team</a>.</p>
            </div>
            <div class="right">
                <p>&copy;Copyrights 2024.</p>
            </div>
        </footer>
    </div>
</body>
<body>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const joinRoomButton = document.getElementById('join-room');

        joinRoomButton.addEventListener('click', function() {
            // Display SweetAlert input popup
            Swal.fire({
                title: 'Join Room',
                input: 'text',
                inputPlaceholder: 'Enter Room Code',
                showCancelButton: true,
                confirmButtonText: 'Join',
                cancelButtonText: 'Cancel',
                inputValidator: (value) => {
                    if (!value) {
                        return 'Room code is required';
                    }
                }
            }).then((result) => {
                const roomCode = result.value;
                window.location.href = '/room/' + roomCode
            });
        });

        // Function to retrieve CSRF token from cookie
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    });
</script>

</html>

templates/web/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <link rel="icon" href="images/music-favicon.jpg">
    <title>SyncX | Home</title>
</head>
<body>
    <div class="bg flex">
        <header class="main">
            <h1 class="left"><span>Sync</span>X.</h1>
            <ul>
                <li><span>A</span></li>
            </ul>
        </header>
        <section id="hero">
            <section class="wrapper">
                <div class="left">
                    <h1>ENJOY <br> THE SONG <br> <span>TOFETHER.</span> </h1>
                </div>
                <div class="right">
                    <button>Create Room</button>
                    <p>Create room and enjoy the music with your friends.</p>
                    <button>Join Room</button>
                    <p>Join others room with redeem code and enjoy the music together.</p>
                </div>
            </section>
        </section>
        <footer>
            <div class="left">
                <p>Developed by <a href="https://www.instagram.com/nexift.team/" target="_blank" title="https://www.instagram.com/nexift.team/">Nexift.Team</a>.</p>
            </div>
            <div class="right">
                <p>&copy;Copyrights 2024.</p>
            </div>
        </footer>
    </div>
</body>
</html>

templates/web/music.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SyncX | Music Room</title>
    <link rel="icon" href="images/music-favicon.jpg">
    <link rel="stylesheet" href="{% static 'css/music.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
</head>
<body>
<section class="sidemain">
    <aside class="sidebar">
        <div class="top">
            <div class="logo">
                <img src="{% static 'images/room.png' %}" alt="icon">
                <h2>{{room.code}}</h2>
            </div>
            <span class="label">created by</span>
            <h4>{{room.admin_name}}</h4>
        </div>
        <h5>Joined Users</h5>
        <hr/>
        <ul class="links">
            {% for user in room.users.all %}
                <li>
                    <h3 >{{user.first_name}}</h3>
                    <span>Joined</span>
                </li>
            {% endfor %}
            <div class="below">
                {% if request.user == room.admin %}
                    <button class="end-room">End Room</button>
                {% else %}
                    <button class="leave-room">Leave Room</button>
                {% endif %}
            </div>
        </ul>
    </aside>
</section>
<section class="main">
    <section class="one">
        <div class="animation">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </section>
    <section class="two">
        <div class="wrapper">
            <div class="img-area">
                <img src="{% static 'images/music-cd.png' %}" alt="image" />
            </div>
            <div class="song-details">
                <p class="name"></p>
                <p class="artist"></p>
                {% if request.user == room.admin %}
                    <div class="import">
<form enctype="multipart/form-data" id="music-upload-form" action="{% url 'web:upload_music' room.code %}" method="POST">
                            <label for="music-file">
                                <span>
                                    <img src="{% static 'images/upload-music.png' %}" alt="icon">
                                </span>
                            </label>
                            {{ form.file }}
                            <button type="submit"><p>Upload</p></button>
                        </form>
                    </div>
                {% endif %}
            </div>
            <div class="progress-area">
                <div class="progress-bar">
                    <audio id="main-audio" autoplay>
                        <source src="{{media_root}}{{files.file}}" type="audio/mpeg">
                    </audio>
                </div>
                <div class="song-timer">
                    <span class="current-time">0:00</span>
                    <span class="max-duration">0:00</span>
                </div>
            </div>
                <div class="controls">
            {% if request.user == room.admin %}
                    <i id="repeat-plist" class="material-icons" title="Playlist looped">repeat</i>
                    <i id="prev" class="material-icons">skip_previous</i>
            {% endif %}
                    <div class="play-pause">
                        <i class="material-icons play">play_arrow</i>
                    </div>
            {% if request.user == room.admin %}
                    <i id="next" class="material-icons">skip_next</i>
                    <i id="more-music" class="material-icons">queue_music</i>
             {% endif %}
                </div>
            <div class="music-list">
                <div class="header">
                    <div class="row">
                        <i class="list material-icons">queue_music</i>
                        <span>Music list</span>
                    </div>
                    <i id="close" class="material-icons">close</i>
                </div>
                <ul></ul>
            </div>
        </div>
    </section>
    <section class="one">
        <div class="animation">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
    </section>
</section>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="js/music-list.js"></script>
<script src="js/script.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    $(document).ready(function() {
        var audio = document.getElementById('main-audio');
        var playPauseButton = $('.play-pause i');
        var currentTimeDisplay = $('.current-time');
        var maxDurationDisplay = $('.max-duration');
        var isPlaying = false;

        function updateTimeDisplay() {
            var currentTime = formatTime(audio.currentTime);
            var duration = formatTime(audio.duration);
            currentTimeDisplay.text(currentTime);
            maxDurationDisplay.text(duration);
        }

        function formatTime(time) {
            var minutes = Math.floor(time / 60);
            var seconds = Math.floor(time % 60);
            return minutes + ':' + (seconds < 10 ? '0' : '') + seconds;
        }

        function togglePlayPause() {
            if (isPlaying) {
                audio.pause();
                isPlaying = false;
                playPauseButton.text('play_arrow');
            } else {
                audio.play();
                isPlaying = true;
                playPauseButton.text('pause');
            }
        }

        playPauseButton.click(function() {
            togglePlayPause();
        });

        audio.addEventListener('timeupdate', function() {
            updateTimeDisplay();
            if (isPlaying) {
                sendCurrentTime();
            }
        });

        function sendCurrentTime() {
            var position = audio.currentTime;
            var length = audio.duration;
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '/toggle_playback/{{ room.code }}',
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                data: {
                    position: position,
                    length: length
                },
                success: function(response) {
                    console.log('Current time updated successfully');
                },
                error: function(error) {
                    console.error('Error updating current time:', error);
                }
            });
        }

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        setInterval(function() {
            if (isPlaying) {
                sendCurrentTime();
            }
        }, 1000);

        $('#music-upload-form').submit(function(event) {
    // Prevent default form submission
    event.preventDefault();

    // Get the action URL from the form's action attribute
    var actionUrl = $(this).attr('action');

    // Get form data
    var formData = new FormData($(this)[0]);
    var csrftoken = getCookie('csrftoken');

    // Send form data using AJAX
    $.ajax({
        url: actionUrl, // Use the extracted action URL here
        type: 'POST',
        headers: {
            'X-CSRFToken': csrftoken
        },
        data: formData,
        cache: false,
        contentType: false,
        processData: false,
        success: function(response) {
            Swal.fire({
                icon: 'success',
                title: 'Success!',
                text: 'Music uploaded successfully.',
            });
        },
        error: function(error) {
            // Handle error response
            console.error('Error uploading music:', error);
            // Display error message to the user, if needed
        }
    });
});


{% if not request.user == room.admin  %}
function receivePlaybackStatusForNonAdmin() {
    $.ajax({
        url: '/get_playback_status/{{room.code}}',
        method: 'GET',
        success: function(response) {
            var playbackStatus = response.is_playing;
            console.log(response);
            var currentTime = response.current_position;

            if (playbackStatus === true) {
                isPlaying = true;
                audio.play();
                playPauseButton.text('pause');
            } else {
                audio.pause();
                isPlaying = false;
                playPauseButton.text('play_arrow');
            }

            audio.currentTime = currentTime;
            updateTimeDisplay();
        },
        error: function(error) {
            console.error('Error fetching playback status:', error);
        }
    });
}

setInterval(function() {
    receivePlaybackStatusForNonAdmin();
}, 1000);
{% endif %}

        function leaveRoom() {
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '/leave_room/{{ room.code }}',
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function(response) {
                    // Handle success response
                    console.log('Left room successfully');
                    window.location.href = "/";
                    // Redirect to some page or perform any other action
                },
                error: function(error) {
                    // Handle error response
                    console.error('Error leaving room:', error);
                }
            });
        }

        // Function to handle ending the room
        function endRoom() {
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                url: '/delete_room/{{ room.code }}',
                type: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken
                },
                success: function(response) {
                    // Handle success response
                    console.log('Room ended successfully');
                    window.location.href = "/";
                    // Redirect to some page or perform any other action
                },
                error: function(error) {
                    // Handle error response
                    console.error('Error ending room:', error);
                }
            });
        }
         $('button.leave-room').click(function() {
            leaveRoom();
        });

        // Event listener for end room button click
        $('button.end-room').click(function() {
            endRoom();
        });
    });
</script>
</body>
</html>

templates/web/playing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{room.code}}
    {{room.admin_name}}
    {% for user in room.users.all %}
        {{user.first_name}}
    {% endfor %}
    <ul>
        {% for file in files %}
            <li>
                <audio id="audio">
                    <source src="{{media_root}}{{file.file}}" type="audio/mpeg">
                </audio>
                {% if request.user == room.admin %}
                <button class="play" data-src="{{media_root}}{{file.file}}">Play</button>
                <button class="pause">Pause</button>
                <button class="skip">Skip</button>
                <button class="delete" data-id="{{file.id}}">Delete</button>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
</body>
<script>
const audio = document.getElementById('audio');


const logPlaybackInfo = setInterval(() => {
    console.log("Current time:", audio.currentTime);
    console.log("Total duration:", audio.duration);
}, 1000);


const playButton = document.querySelector('.play');

playButton.addEventListener('click', async () => {
    audio.play();
});

const pauseButton = document.querySelector('.pause');

pauseButton.addEventListener('click', async () => {
    audio.pause();
});

const skipButton = document.querySelector('.skip');

skipButton.addEventListener('click', async () => {
});

const deleteButton = document.querySelector('.delete');

deleteButton.addEventListener('click', async () => {
});


</script>
</html>